name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    - run: npx playwright install

    - name: Executando testes
      run: npm run test:headless

    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      with:
        name: Relatorios-Testes
        path: |
          report/desktop.html
          report/tablet.html
          report/mobile.html
